### ISSUE TITLE
Move coderetreat.org to netlify

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/orga-tasks#1]
Moving to netlify gives us more control over the build process, allows us to add jekyll plugins and such. Also comes with out-of-the-box SSL certificates :+1:

Requires help from @coreyhaines so we can switch over nameserver entries.

**Comment by thodorisbais** [comment]
Wow, what a coincidence, I was thinking about an automated build process today.
I would be interested in picking this up with the right guidance of @coreyhaines .

**Comment by coreyhaines** [comment]
Let me know how I can help. I'm happy to jump in and point the names to the other places.

This also is perhaps a better solution than the issue I created in the github.io repo. Let me know when you all need anything.

**Comment by rradczewski** [comment]
Thanks @coreyhaines! Everything is already setup, all you have to do is point the records for coderetreat.org to netlify. [This is a very elaborate guide on how to do that](https://www.netlify.com/docs/custom-domains/). Once you make the changes it should just work (:tm:)

The CNAME record should be as follows:
```
www CNAME coderetreat-org.netlify.com.
```

The A Record should be as follows:
```
@	A	104.198.14.52
```

Here's how it looks like for one of my domains:
![image](https://user-images.githubusercontent.com/418117/37477773-cc890f4c-2878-11e8-8141-ae5099c37cac.png)

I didn't go with Netlify's DNS because I have GSuite running on that domain, I imagine that's the case with coderetreat.org as well.

**Comment by coreyhaines** [comment]
Okay, I added the records. Feel free to check it out while it propagates.
Let me know here if it has any issues, and I'll make any updates.

On Thu, Mar 15, 2018 at 11:52 AM, Raimo Radczewski <notifications@github.com

**Comment by coreyhaines** [comment]
per the documentation, I created
ALIAS codertreat.org -> coderetreat-org.netlify.com
CNAME www -> coderetreat-org.netlify.com

**Comment by rradczewski** [comment]
Works :heart_eyes:, thanks! I installed a LetsEncrypt certificate as well :+1:

**Comment by coreyhaines** [comment]
Is there a way for netlify to auto-redirect to https? It would be good to
just not allow http at all

**Comment by rradczewski** [comment]
Yepp, we can create [a redirect](https://www.netlify.com/docs/redirects/) that will redirect all http traffic to https. Will do that 👌

**Comment by rradczewski** [comment]
https://github.com/coderetreat/coderetreat.github.io/commit/5d4186fdc519ee9c3173c6ff5ed430538319a500 adds a redirect rule that will redirect all HTTP traffic to HTTPS :ok_hand:
